<?php

/**
 * Implements hook_menu()
 */
function directorio_menu() {
	$items = array();

	$items["directorio"] = array(
		'title' => 'Directorio',
		'description' => 'Listado de contactos en el sitio',
		'page callback' => 'directorio_page',
		'access arguments' => array("ver directorio"),
		'type' => MENU_NORMAL_ITEM
	);

	// $items["directorio/buscar"] = array(

	// );

	// $items["directorio/buscar/nombre/%"] = array(

	// );

	// $items["directorio/buscar/extension/%"] = array(

	// );

	$items["contactos/agregar"] = array(
		'title' => 'Agregar contacto',
		'description' => 'Agregar un nuevo contacto',
		'type' => MENU_NORMAL_ITEM,
		'page callback' => 'drupal_get_form',
		'page arguments' => array("directorio_agregarContactoForm"),
		'access arguments' => array("agregar contacto"),
	);

	$items["contactos/ver/%"] = array(
		'title callback' => 'contactosTitle',
		'title arguments' => array(1, 2),
		'description' => 'Ver contacto',
		'page callback' => 'contactosVer',
		'page arguments' => array(2),
		'access arguments' => array("ver directorio"),
		'type' => MENU_CALLBACK
	);

	// $items["contactos/editar/%"] = array(

	// );

	// $items["eliminar/%"] = array(

	// );

	return $items;
}


/**
 * Title callback
 */
function contactosTitle($op, $cid) {
	$contacto = contactosLoad($cid);

	$output = "";
	switch($op) {
		case "ver": 
			$output = contactoRealname($contacto);
		break;

		case "editar":
			$output = t("Editar contacto: !contacto", array("!contacto" => contactoRealname($contacto)));
		break;
	}

	return $output;
}

/**
 * Formatea el nombre de un contacto
 *
 * @return string nombre del contacto
 */
function contactoRealname($contacto) {
	if(is_array($contacto)) {
		return $contacto["nombre"] . " " . $contacto["apellido_paterno"] . " " . $contacto["apellido_materno"];
	}
	else if(is_object($contacto)) {
		return $contacto->nombre . " " . $contacto->apellido_paterno . " " . $contacto->apellido_materno;
	}
	else {
		return NULL;
	}
}

/**
 * Page callback para contactos/ver/%
 */
function contactosVer($cid) {
	global $user;
	$contacto = contactosLoad($cid);

	$persona = new stdClass();

	//Datos publicos, todo mundo los puede ver
	$persona->nombre = $contacto->nombre;
	$persona->apellido_paterno = $contacto->apellido_paterno;
	$persona->apellido_materno = $contacto->apellido_materno;
	$persona->nombre_completo = contactoRealname($contacto);
	$persona->departamento = $contacto->departamento;
	$persona->telefono_oficina = $contacto->telefono_oficina;

	//139.111.%.%
	$ip = explode(".", ip_address());

	if (($ip[0] == "139" && $ip[0] == "111") || ($ip[0] == "127" && $ip[1] == "0" && $ip[2] == "0" && $ip[3] == "1")) {
			
			$persona->email_trabajo = $contacto->email_trabajo;
			$persona->oficina_extension = $contacto->oficina_extension;

			if(isset($contacto->telefono_celular)){
				$persona->telefono_celular = $contacto->telefono_celular;
			}
	}

	if(user_is_logged_in()){
		$persona->email_trabajo = $contacto->email_trabajo;
		$persona->oficina_extension = $contacto->oficina_extension;

		if(isset($contacto->telefono_celular)){
			$persona->telefono_celular = $contacto->telefono_celular;
		}
	}


	if(user_access("ver datos privados") || $user->mail == $contacto->email_trabajo){
		$persona->email_trabajo = $contacto->email_trabajo;
		$persona->email_personal = $contacto->email_personal;
		$persona->telefono_casa = $contacto->telefono_casa;
		$persona->oficina_extension = $contacto->oficina_extension;
	}
	
	return theme('ver_contacto', array('contacto' => $persona ));
}


function directorio_theme(&$existing, $type, $theme, $path){
	$items = array();

	$items['ver_contacto'] = array(
		'variables' => array(
			'contacto' => NULL
		),
		'template' => 'contacto-ver'
	);

	$items['directorio'] = array(
			'variables' => array(
				'contactos' => NULL
			),
			'template' => 'directorio'
		);
	
	return $items;
}
/**
 * Funcion preproces en un modulo siempre empieza con template
 */
function template_preprocess_ver_contacto(&$variables){
	$variables["ultima_consulta"] = format_date(time(), 'short');
}

/**
 * Load contacto
 * @return object contacto
 */
function contactosLoad($cid) {
	return db_select("contactos", "c")
		->fields("c")
		->condition("c.cid", $cid, "=")
		->execute()
		->fetchObject();
}

/**
 * funcion para consultar todos los contactos de la tabla
 *@param string $departamento departamento a consultar, opcional
 *@return array resultadosde la tabla de contactos,
 */

function contactosGetAll($departamento = NULL){
	if(isset($departamento)){
		$query = db_query("SELECT * FROM {contacos} c WHERE c.departamento = :departamento ORDER BY c.cid ASC", array(":departamento" => $departamento ));
	}
	else{
		$query = db_query("SELECT * FROM {contactos} c ORDER BY c.cid ASC");
	}
	$results = array();

	foreach ($query as $result) {
		$results[$result->cid] = $result;
	}

	return $results;
}

/**
 * Callback principal de /directorio
 * Muestra un listado de contactos en el sitio
 */
function directorio_page() {
	$contactos = contactosGetAll();
	if($contactos){

		$header = array(
			'nombre' => array(
				'data' => t("Nombre"),
				'field' => 'nombre'
			),
			'apellido_paterno' => array(
				'data' => t("Apellido Paterno"),
				'field' => 'apellido_paterno'
			),
			'apellido_materno' => array(
				'data' => t("Apellido Materno"),
				'field' => 'apellido_materno'
			),
			'departamento' => array(
				'data' => t("Departamento"),
				'field' => 'departamento'
			),
			'ver' => array()
		);

		$rows = array();

		foreach ($contactos as $contacto) {
			$row["nombre"] = $contacto->nombre;
			$row["apellido_paterno"] = $contacto->apellido_paterno;
			$row["apellido_materno"] = $contacto->apellido_materno;
			$row["departamento"] = $contacto->departamento;
			$row["ver"] = l(t("Ver"), "contactos/ver/" . $contacto->cid);

			$rows[] = $row;
		}

		return theme("table", array("header" => $header, "rows" => $rows));
	}
	else{
		drupal_set_message(t("No se encuentran contactos"));
		return NULL;
	}
}

/**
 * Implements hook_permission()
 */
function directorio_permission() {
	return array(
		'ver directorio' => array(
			'title' => t("Ver el directorio de contactos"),
			'description' => t("Permite mostrar el directorio de contactos")
		),
		'agregar contacto' => array(
			'title' => t("Agregar contactos"),
			'description' => t("Permite crear nuevos contactos en el directorio")
		),
		'ver datos privados' => array(
			'title' => t("Ver Datos Privados"),
			'description' => t("Permite ver datos privados de un contacto")
		)
	);
}

/**
 * Callback para contactos/agregar
 * Muestra la forma para agregar un contacto
 */
function directorio_agregarContactoForm($form) {
	$form = array();

	$form["nombre"] = array(
		'#type' => 'textfield',
		'#title' => t("Nombre"),
		'#required' => TRUE,
		'#description' => t("Escriba el nombre o los nombres del contacto")
	);

	$form["apellido_paterno"] = array(
		'#type' => 'textfield',
		'#title' => t("Apellido paterno"),
		'#required' => TRUE,
		'#description' => t("Escriba el apellido paterno")
	);

	$form["apellido_materno"] = array(
		'#type' => 'textfield',
		'#title' => t("Apellido materno"),
		'#required' => FALSE,
		'#description' => t("Escriba el apellido materno. Este campo es opcional.")
	);

	$form["departamento"] = array(
		'#type' => 'select',
		'#title' => t("Departamento"),
		'#required' => TRUE,
		'#description' => t("Seleccione el departamento al que pertenece esta persona"),
		'#options' => getDepartamento()
	);

	$form["telefono_oficina"] = array(
		'#type' => 'textfield',
		'#title' => t("Teléfono de oficina"),
		'#required' => TRUE,
		'#description' => t("Escriba el teléfono de oficina"),
		'#default_value' => _telefonoDeOficinaDefault()
	);

	$form["oficina_extension"] = array(
		'#type' => 'textfield',
		'#title' => t("Extensión telefónica"),
		'#required' => TRUE,
		'#description' => t("Escriba la extensión telefónica del contacto")
	);

	$form["email_trabajo"] = array(
		'#type' => 'textfield',
		'#title' => t("Correo electrónico del trabajo"),
		'#required' => FALSE,
		'#description' => t("Escriba el correo electrónico del trabajo del contacto")
	);

	$form["email_personal"] = array(
		'#type' => 'textfield',
		'#title' => t("Correo electrónico personal"),
		'#required' => FALSE,
		'#description' => t("Escriba el correo electrónico personal del contacto")
	);

	$form["telefono_casa"] = array(
		'#type' => 'textfield',
		'#title' => t("Teléfono de casa"),
		'#required' => FALSE,
		'#description' => t("Escriba el teléfono de casa")
	);

	$form["telefono_celular"] = array(
		'#type' => 'textfield',
		'#title' => t("Teléfono celular"),
		'#required' => FALSE,
		'#description' => t("Escriba el teléfono celular del contacto")
	);

	$form["actions"] = array(
		'#prefix' => '<div class="actions well">',
		'#suffix' => '</div>'
	);

	$form["actions"]["submit"] = array(
		'#type' => 'submit',
		'#value' => t("Save")
	);

	return $form;
}

/**
 * Submit callback para agregar contactos form
 */
function directorio_agregarContactoForm_submit(&$form, &$form_state) {
	$values = $form_state["values"];
	dsm($values);

	$persona = array(
		'nombre' => $values["nombre"],
		'apellido_paterno' => $values["apellido_paterno"],
		'apellido_materno' => $values["apellido_materno"],
		'departamento' => $values["departamento"],
		'telefono_oficina' => $values["telefono_oficina"],
		'oficina_extension' => $values["oficina_extension"],
		'email_trabajo' => $values["email_trabajo"],
		'email_personal' => $values["email_personal"],
		'telefono_celular' => $values["telefono_celular"],
		'telefono_casa' => $values["telefono_casa"]
	);

	$cid = db_insert("contactos")
		->fields($persona)
		->execute();

	if($cid) {
		drupal_set_message(t("Se insertó con éxito el contacto con id !id", array("!id" => $cid)));
	}
	else {
		drupal_set_message(t("Hubo un error"), "error");
	}
}

/**
 * Listado de departamentos en la compañía
 *
 * @return array listado de departamentos
 */
function getDepartamento() {
	return array(
		'administracion' => t("Administración"),
		'recursos_humanos' => t("Recursos Humanos"),
		'sistemas' => t("Sistemas"),
		'ventas' => t("Ventas")
	);
}


/**
 * Número de teléfono por default de la organización
 * @return  string teléfono de oficina por default
 */
function _telefonoDeOficinaDefault() {
	return "2020-7350";
}


